spring.application.name=leftoverChef

# Configure memory settings
spring.jvm.memory.max=1G
spring.jvm.memory.initial=512M

# Configure server settings
server.tomcat.max-http-form-post-size=32MB
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB
